
server.port=${PORT:8080}


spring.application.name=ai-code-review-agent
spring.ai.mistralai.api-key=${MISTRAL_KEY}
spring.ai.mistralai.base-url=https://api.mistral.ai/v1
spring.ai.mistralai.chat.options.model=mistral-small-latest

# PostgreSQL Database Connection
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Tavily API Key
tavily.api.key=${TAVILY_KEY}

# ApyHub API Key
apihub.api.key=${API_HUB}

# GitHub Personal Access Token
github.token=${GITHUB_PAT}

firebase.service-account.key=/etc/secrets/firebase-service-account.json


firebase.api.key=${FIRE_BASE_KEY}

