spring.application.name=ai-code-review-agent
spring.ai.mistralai.api-key=4Dvy1KiD2oBeRh4N1nYvDUEEqYWnjYCa
spring.ai.mistralai.base-url=https://api.mistral.ai/v1


# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/code_review
spring.datasource.username=postgres
spring.datasource.password=khu123_45
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

