spring.application.name=ai-code-review-agent
spring.ai.mistralai.api-key=4Dvy1KiD2oBeRh4N1nYvDUEEqYWnjYCa
spring.ai.mistralai.base-url=https://api.mistral.ai/v1

spring.ai.mistralai.chat.options.model=mistral-small-latest

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/coderev2
spring.datasource.username=postgres
spring.datasource.password=khu123_45
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Tavily API Key
tavily.api.key=${TAVILY_KEY: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}

# ApyHub API Key
apihub.api.key=${API_HUB:APY0RL2dc2Ks2LrBNLDoF5KmyJe8YfvTjUC6LuogUYrZcGguZpGPkYAuGDEw38TGJhR}

# GitHub Personal Access Token
github.token=${GITHUB_PAT}

spring.security.oauth2.client.registration.github.client-id=Ov23liwrnOTokjHMsuFg
spring.security.oauth2.client.registration.github.client-secret=714174230f17a311c46ce3fca62275ba2b405dff
spring.security.oauth2.client.registration.github.scope=read:user,user:email


# Spring Security OAuth2 Provider Details
#spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
#spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
#spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
#spring.security.oauth2.client.provider.github.user-name-attribute=login

# Server sessions ko cookie ke through track karne ke liye
server.servlet.session.cookie.name=JSESSIONID

# Chrome/Edge browsers ke liye cookie restriction ko easy karne ke liye
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true


firebase.service-account.key=classpath:firebase-service-account.json
firebase.api.key=AIzaSyBC0ebD1kY6yHZra0rKjRvgnRIghezOa08
